name: Run Azure Login with OIDC
on: [push]

permissions:
      id-token: write
      contents: read
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SHOPPINGAPP_AZURE_CREDENTIALS }}
          allow-no-subscriptions: true

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/Docker 
          registryUrl: shoppingappacreg.azurecr.io
          registryUsername: ${{ secrets.SHOPPINGAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SHOPPINGAPP_REGISTRY_PASSWORD }}
          containerAppName: shoppingapp
          resourceGroup: jdev-rg
          imageToBuild: shoppingappacreg.azurecr.io/shoppingapp:${{ github.sha }}
          dockerfilePath: Dockerfile
          allow-no-subscriptions: true

     

